services:
  backend:
    build: ./backend
    ports:
      - "15100:15100"
    environment:
      APP_MODE: dev
      PORT: "15100"
      FRONTEND_URL: http://localhost:15151

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile.dev
    ports:
      - "15151:15151"
    environment:
      VITE_APP_MODE: dev
      VITE_API_BASE_URL: http://localhost:15100
